service: KMD-AS-WIZ

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs4.3
  memorySize: 128
  region: ap-southeast-2
  stage: v0
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  create:
    handler: acwiz/create.create
    events:
      - http:
          path: acwiz
          method: post
          cors: true

  list:
    handler: acwiz/list.list
    events:
      - http:
          path: acwiz
          method: get
          cors: true

  get:
    handler: acwiz/get.get
    events:
      - http:
          path: acwiz/{id}
          method: get
          cors: true

  update:
    handler: acwiz/update.update
    events:
      - http:
          path: acwiz/{id}
          method: put
          cors: true

  delete:
    handler: acwiz/delete.delete
    events:
      - http:
          path: acwiz/{id}
          method: delete
          cors: true
plugins:
  - serverless-finch

custom:
  client:
    bucketName: imylomylo-acwiz
    distributionFolder: vue/dist

resources:
  Resources:
    ACWIZDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
